# Path to the logging file
logging.file.name=logs/app.log

# Logging level configuration
logging.level.root=DEBUG
logging.level.org.springframework=INFO

# Jira base URL
jira.url=https://sphengineering.atlassian.net/
jira.collectorId=78e2c7cd

# Max undo stack depth
undo.depth=3
