name: UgCS GeoHammer build for MacOS
on: [push, workflow_dispatch]
jobs:
  GeoHammer-MacOS-Build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          java-package: 'jdk+fx'
          architecture: 'x64'
      - name: Build with Maven
        run: mvn --batch-mode install -P macos-build
      - name: Staging artifacts
        run: mkdir staging && cp target/*.zip staging
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-Package
          path: staging
          retention-days: 5
