name: GeoHammer build for MS Windows
on: [push, workflow_dispatch]
jobs:
  GeoHammer-Windows-Build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set JDK version and download it
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          java-package: 'jdk+fx'
          architecture: 'x64'
      - name: Install Inno Setup
        run: choco install innosetup -y --no-progress
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn --batch-mode install -P windows-build
      - name: Staging artifacts
        run: mkdir staging && copy target\*.exe staging
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Package
          path: staging
          retention-days: 5
