name: UgCS GeoHammer build for MS Windows
on: [push, workflow_dispatch]
jobs:
  GeoHammer-Windows-Build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          java-package: 'jdk+fx'
          architecture: 'x64'
      - name: Build with Maven
        run: mvn --batch-mode install -P windows-build
      - name: Staging artifacts
        run: mkdir staging && copy target\*.zip staging
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Package
          path: staging
          retention-days: 5
